version: '3'

services:

  app:
    tty: true
    environment: &app-environment
      DATABASE_URL: postgres://admin:admin@db/bot
      TELEGRAM_TOKEN: 1129177767:AAHpYZQ7G0vcmU_fziDEV4ju1xarGI4QmOI
      FLASK_APP: app:app
      FLASK_DEBUG: "1"
      FLASK_ENV: development

    # set environment variable CURRENT_UID=$(id -u):$(id -g) before running
    # service for generation files, like migration
    user: ${CURRENT_UID}
    build: .
    image: roslynka-bot
    ports: ["5000:5000"]
    volumes: ['.:/work']
    depends_on: [db]
    entrypoint: flask
    command: run --host 0.0.0.0

  db:
    image: postgres
    ports: ["5432:5432"]
    volumes:
      - ./.database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bot
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
