# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push new tag
on:
  push:
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            # Connect options
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            passphrase: ${{ secrets.SSH_PASSPHRASE }}
            port: ${{ secrets.SSH_PORT }}

            script_stop: true  # stop after first failure
            script: |
              echo $PWD
              whoami
              source env/bin/activate
              cd bot
              git pull
              pip install -r requirements.txt
              uwsgi --ini=bot.ini

